// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ptlk.RedisSnmp.Data;

#nullable disable

namespace Ptlk.RedisSnmp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708053957_RemovePointPollingAndSetFlags")]
    partial class RemovePointPollingAndSetFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.CommandExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CommandId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("RedisKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("redis_key");

                    b.Property<string>("RequestedPayload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_payload");

                    b.Property<string>("ResultPayload")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_command_executions");

                    b.HasIndex("CommandId")
                        .IsUnique()
                        .HasDatabaseName("ix_command_executions_command_id");

                    b.HasIndex("RedisKey")
                        .HasDatabaseName("ix_command_executions_redis_key");

                    b.ToTable("command_executions", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<int>("MibSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mib_set_id");

                    b.Property<string>("ModuleIdentityOid")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("module_identity_oid");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("module_name");

                    b.Property<string>("RawContent")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_content");

                    b.Property<string>("StoredPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_status");

                    b.HasKey("Id")
                        .HasName("pk_mib_files");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_mib_files_hash");

                    b.HasIndex("MibSetId", "FileName")
                        .HasDatabaseName("ix_mib_files_mib_set_id_file_name");

                    b.ToTable("mib_files", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibImportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("ImportId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("import_id");

                    b.Property<int?>("MibSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mib_set_id");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("version_name");

                    b.HasKey("Id")
                        .HasName("pk_mib_import_jobs");

                    b.HasIndex("ImportId")
                        .IsUnique()
                        .HasDatabaseName("ix_mib_import_jobs_import_id");

                    b.HasIndex("MibSetId")
                        .HasDatabaseName("ix_mib_import_jobs_mib_set_id");

                    b.ToTable("mib_import_jobs", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Access")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("access");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("MibFileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mib_file_id");

                    b.Property<int?>("MibSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mib_set_id");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("module_name");

                    b.Property<string>("NumericOid")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("numeric_oid");

                    b.Property<string>("SymbolicName")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbolic_name");

                    b.Property<string>("Syntax")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("syntax");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("version_name");

                    b.HasKey("Id")
                        .HasName("pk_mib_nodes");

                    b.HasIndex("MibFileId")
                        .HasDatabaseName("ix_mib_nodes_mib_file_id");

                    b.HasIndex("SymbolicName")
                        .HasDatabaseName("ix_mib_nodes_symbolic_name");

                    b.HasIndex("MibSetId", "NumericOid")
                        .HasDatabaseName("ix_mib_nodes_mib_set_id_numeric_oid");

                    b.HasIndex("MibSetId", "SymbolicName")
                        .HasDatabaseName("ix_mib_nodes_mib_set_id_symbolic_name");

                    b.HasIndex("VersionName", "NumericOid")
                        .HasDatabaseName("ix_mib_nodes_version_name_numeric_oid");

                    b.ToTable("mib_nodes", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mib_sets");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mib_sets_name");

                    b.ToTable("mib_sets", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibSetValidationIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<int>("MibSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mib_set_id");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("module_name");

                    b.Property<string>("NumericOid")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("numeric_oid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("SymbolicName")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbolic_name");

                    b.HasKey("Id")
                        .HasName("pk_mib_set_validation_issues");

                    b.HasIndex("MibSetId", "Code")
                        .HasDatabaseName("ix_mib_set_validation_issues_mib_set_id_code");

                    b.HasIndex("MibSetId", "Severity")
                        .HasDatabaseName("ix_mib_set_validation_issues_mib_set_id_severity");

                    b.ToTable("mib_set_validation_issues", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.RedisMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("RedisKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("redis_key");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_redis_mappings");

                    b.HasIndex("RedisKey")
                        .IsUnique()
                        .HasDatabaseName("ix_redis_mappings_redis_key");

                    b.HasIndex("SourcePath")
                        .IsUnique()
                        .HasDatabaseName("ix_redis_mappings_source_path");

                    b.ToTable("redis_mappings", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpAgentConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CredentialConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credential_config_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<int>("PollingRateMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("polling_rate_ms");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<int?>("PreferredMibSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preferred_mib_set_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<string>("SnmpVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("snmp_version");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_ms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_snmp_agent_configs");

                    b.HasIndex("AgentId")
                        .IsUnique()
                        .HasDatabaseName("ix_snmp_agent_configs_agent_id");

                    b.HasIndex("CredentialConfigId")
                        .HasDatabaseName("ix_snmp_agent_configs_credential_config_id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("ix_snmp_agent_configs_display_name");

                    b.HasIndex("PreferredMibSetId")
                        .HasDatabaseName("ix_snmp_agent_configs_preferred_mib_set_id");

                    b.ToTable("snmp_agent_configs", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpCredentialConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AuthProtocol")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_protocol");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PrivProtocol")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("priv_protocol");

                    b.Property<string>("ProtectedAuthPassword")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_auth_password");

                    b.Property<string>("ProtectedCommunity")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_community");

                    b.Property<string>("ProtectedPrivPassword")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_priv_password");

                    b.Property<string>("ProtectedReadCommunity")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_read_community");

                    b.Property<string>("ProtectedWriteCommunity")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_write_community");

                    b.Property<string>("SecurityLevel")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_level");

                    b.Property<string>("SecurityName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_snmp_credential_configs");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_snmp_credential_configs_name");

                    b.ToTable("snmp_credential_configs", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AgentConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_config_id");

                    b.Property<string>("AgentId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CommandId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("NumericOid")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("numeric_oid");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<int?>("PointConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("point_config_id");

                    b.HasKey("Id")
                        .HasName("pk_snmp_log_entries");

                    b.HasIndex("AgentConfigId")
                        .HasDatabaseName("ix_snmp_log_entries_agent_config_id");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_snmp_log_entries_command_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_snmp_log_entries_created_at");

                    b.HasIndex("PointConfigId")
                        .HasDatabaseName("ix_snmp_log_entries_point_config_id");

                    b.HasIndex("AgentId", "NumericOid")
                        .HasDatabaseName("ix_snmp_log_entries_agent_id_numeric_oid");

                    b.ToTable("snmp_log_entries", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpPointConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("access");

                    b.Property<int>("AgentConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_config_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("MibAccess")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("mib_access");

                    b.Property<string>("MibDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("mib_description");

                    b.Property<string>("MibLabel")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT")
                        .HasColumnName("mib_label");

                    b.Property<string>("MibModule")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("mib_module");

                    b.Property<int?>("MibSetIdUsedForMapping")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mib_set_id_used_for_mapping");

                    b.Property<string>("MibSyntax")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("mib_syntax");

                    b.Property<string>("NumericOid")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("numeric_oid");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_name");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_snmp_point_configs");

                    b.HasIndex("MibSetIdUsedForMapping")
                        .HasDatabaseName("ix_snmp_point_configs_mib_set_id_used_for_mapping");

                    b.HasIndex("SourcePath")
                        .IsUnique()
                        .HasDatabaseName("ix_snmp_point_configs_source_path");

                    b.HasIndex("AgentConfigId", "PointName")
                        .IsUnique()
                        .HasDatabaseName("ix_snmp_point_configs_agent_config_id_point_name");

                    b.ToTable("snmp_point_configs", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpTrapLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("MibLabelsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("mib_labels_json");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_address");

                    b.Property<string>("TrapOid")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("trap_oid");

                    b.Property<string>("VarbindsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("varbinds_json");

                    b.HasKey("Id")
                        .HasName("pk_snmp_trap_log_entries");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_snmp_trap_log_entries_received_at");

                    b.HasIndex("AgentId", "TrapOid")
                        .HasDatabaseName("ix_snmp_trap_log_entries_agent_id_trap_oid");

                    b.ToTable("snmp_trap_log_entries", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpTrapRuleConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("TrapOid")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("trap_oid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_snmp_trap_rule_configs");

                    b.HasIndex("AgentId", "TrapOid")
                        .IsUnique()
                        .HasDatabaseName("ix_snmp_trap_rule_configs_agent_id_trap_oid");

                    b.ToTable("snmp_trap_rule_configs", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SystemLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CommandId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.HasKey("Id")
                        .HasName("pk_system_log_entries");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_system_log_entries_command_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_system_log_entries_created_at");

                    b.HasIndex("Category", "Level")
                        .HasDatabaseName("ix_system_log_entries_category_level");

                    b.ToTable("system_log_entries", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibFile", b =>
                {
                    b.HasOne("Ptlk.RedisSnmp.Models.MibSet", "MibSet")
                        .WithMany("Files")
                        .HasForeignKey("MibSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mib_files_mib_sets_mib_set_id");

                    b.Navigation("MibSet");
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibImportJob", b =>
                {
                    b.HasOne("Ptlk.RedisSnmp.Models.MibSet", "MibSet")
                        .WithMany()
                        .HasForeignKey("MibSetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mib_import_jobs_mib_sets_mib_set_id");

                    b.Navigation("MibSet");
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibNode", b =>
                {
                    b.HasOne("Ptlk.RedisSnmp.Models.MibFile", "MibFile")
                        .WithMany("Nodes")
                        .HasForeignKey("MibFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mib_nodes_mib_files_mib_file_id");

                    b.HasOne("Ptlk.RedisSnmp.Models.MibSet", "MibSet")
                        .WithMany("Nodes")
                        .HasForeignKey("MibSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_mib_nodes_mib_sets_mib_set_id");

                    b.Navigation("MibFile");

                    b.Navigation("MibSet");
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibSetValidationIssue", b =>
                {
                    b.HasOne("Ptlk.RedisSnmp.Models.MibSet", "MibSet")
                        .WithMany("ValidationIssues")
                        .HasForeignKey("MibSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mib_set_validation_issues_mib_sets_mib_set_id");

                    b.Navigation("MibSet");
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpAgentConfig", b =>
                {
                    b.HasOne("Ptlk.RedisSnmp.Models.SnmpCredentialConfig", "CredentialConfig")
                        .WithMany()
                        .HasForeignKey("CredentialConfigId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_snmp_agent_configs_snmp_credential_configs_credential_config_id");

                    b.HasOne("Ptlk.RedisSnmp.Models.MibSet", "PreferredMibSet")
                        .WithMany()
                        .HasForeignKey("PreferredMibSetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_snmp_agent_configs_mib_sets_preferred_mib_set_id");

                    b.Navigation("CredentialConfig");

                    b.Navigation("PreferredMibSet");
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpLogEntry", b =>
                {
                    b.HasOne("Ptlk.RedisSnmp.Models.SnmpAgentConfig", "AgentConfig")
                        .WithMany()
                        .HasForeignKey("AgentConfigId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_snmp_log_entries_snmp_agent_configs_agent_config_id");

                    b.HasOne("Ptlk.RedisSnmp.Models.SnmpPointConfig", "PointConfig")
                        .WithMany()
                        .HasForeignKey("PointConfigId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_snmp_log_entries_snmp_point_configs_point_config_id");

                    b.Navigation("AgentConfig");

                    b.Navigation("PointConfig");
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpPointConfig", b =>
                {
                    b.HasOne("Ptlk.RedisSnmp.Models.SnmpAgentConfig", "AgentConfig")
                        .WithMany("Points")
                        .HasForeignKey("AgentConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_snmp_point_configs_snmp_agent_configs_agent_config_id");

                    b.HasOne("Ptlk.RedisSnmp.Models.MibSet", "MibSetUsedForMapping")
                        .WithMany()
                        .HasForeignKey("MibSetIdUsedForMapping")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_snmp_point_configs_mib_sets_mib_set_id_used_for_mapping");

                    b.Navigation("AgentConfig");

                    b.Navigation("MibSetUsedForMapping");
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibFile", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.MibSet", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Nodes");

                    b.Navigation("ValidationIssues");
                });

            modelBuilder.Entity("Ptlk.RedisSnmp.Models.SnmpAgentConfig", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
